version: '1.0'
services:
  auth-db:
    image: postgres:15-alpine
    container_name: auth-db
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=auth
    networks:
      - ecommerce
