version: '1.0'
services:
  auth-db:
    image: postgres:15-alpine
    container_name: auth-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=auth
    networks:
      - ecommerce
  product-db:
    image: postgres:15-alpine
    container_name: product-db
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "5433:5432"  # Changed the host port to 5433 for product-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=product
    networks:
      - ecommerce

  order-cart-db:
    image: postgres:15-alpine
    container_name: order-cart-db
    deploy:
      mode: replicated
      replicas: 1
    ports:
      - "5434:5432"  # Changed the host port to 5434 for order-cart-db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=order-cart
    volumes: 
      - ./db-data/order-cart-postgres/:/var/lib/postgresql/data  # Ensure separate volumes for each db
    networks:
      - ecommerce


networks:
  ecommerce:
    driver: bridge
